### ISSUE TITLE
styles.css not specific enough.

### ISSUE THREAD

**Issue by danmarsden** [skillsoftadmin/moodle-mod_percipio#1]
in your styles.css you define a number of generic styles that could clash with core moodle code or other locations where simliar names are used. 

Moodle helpfully adds a number of classes to the body tag based on the path that you can use such as:
eg if you are have a file in mod/assign you would see the following class added to the body tag
path-mod-assign
so if you have an item with the class "filething" on the page you would target it like:
```
.path-mod-assign .filething {
   color: red;
}
```

Please make sure your css classes in styles.css are specific enough so they cannot clash with other core code.
note - this is a blocker for approval in the plugins db.

**Comment by pchakraborty13** [comment]
Hello Dan,

We have fixed the mentioned issue and submitted the plugin for re-approval. We are really thankful for your important suggestions which helped us to make the plugin better. Thank you.

**Comment by skillsoftadmin** [comment]
Hello Dan,
We have fixed the mentioned issue and submitted the plugin for re-approval. We are really thankful for your important suggestions which helped us to make the plugin better. 
Thank you.

**Comment by danmarsden** [comment]
Hi @skillsoftadmin - it doesn't look like you understood this one completely?

css styles like:
```
.img-cover {
```
should be:
```
.path-mod-assign .img-cover {
```

but there are other examples in that file that are also still wrong.

**Comment by danmarsden** [comment]
.loader, .loader_backgroundm, .top etc

**Comment by skillsoftadmin** [comment]
Hi Dan,
We have done the changes, kindly requesting you to review it.
Thank you for your suggestions!

**Comment by danmarsden** [comment]
looks a lot better thanks - I do wonder if your "spin" animation name might be a little fragile, but I'm not going to block approval on it. (might be better calling it something like percipio-spin just in case something in core moodle decides to use a "spin" animation at some point.)
