### ISSUE TITLE
Moodle code already includes jquery

### ISSUE THREAD

**Issue by danmarsden** [skillsoftadmin/moodle-mod_percipio#4]
You seem to add in the jquery 3.4.0 version of JS to your plugin - please don't do this - Moodle already includes Jquery in the core files so you should be able to leverage the version already in the core moodle codebase..

From memory - 3.4.0 actually contains some security issues that would also get picked up in a security audit so better to just leverage the version in Moodle and let Moodle handle upgrades of the library etc.

Please note... If you do add 3rd party libraries to your plugin, (I don't think you need to in this case and you can probably just delete it.) but for future reference...

When including an external library in your plugin, you must include a thirdpartylibs.xml file that includes the name, location and license of the library.
More information on this is here:
https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml
And here:
https://docs.moodle.org/dev/Plugin_with_third_party_libraries

One of the other advantages of using this is that Moodle's codechecker automatically ignores any files included in the location specificed in the thirdpartylibs.xml file.

Please note - this is typically a blocker for approval in the plugins db.

**Comment by skillsoftadmin** [comment]
Hello Dan,
We have fixed the mentioned issue and submitted the plugin for re-approval. We are really thankful for your important suggestions which helped us to make the plugin better. 
Thank you.

**Comment by danmarsden** [comment]
uh... can you please go back through the reported issues you've just closed and make sure you've actually fixed them?

I still see the jquery lib file in your js folder:/
https://github.com/skillsoftadmin/moodle-mod_percipio/blob/master/js/jquery.min.js

**Comment by skillsoftadmin** [comment]
Hi Dan, can you please check once again, because we are not able to see the file reference anywhere in the code.
![image](https://user-images.githubusercontent.com/103200973/165460178-34a1a8e1-8943-4424-a525-04c31757b05c.png)

**Comment by skillsoftadmin** [comment]
Hi Dan, 
that was a miss from our side while pushing it to this Github. we have solved this now. And we have also went through your other comments and incorporated the changes.
Thank you so much for giving your time to review this.
Appreciate your efforts!
